### ISSUE TITLE
A bug found when trying to execute conditionals.nat example

### ISSUE THREAD

**Issue by ankiedos** [rbaltrusch/python_interpreter#7] opened 2021-11-11 12:03 UTC
**Describe the bug**
Index out of range exception raised

**To Reproduce**
1. Copy examples\conditionals.nat to test.nat for proper executing
2. Run python interpreter\main.py

**Expected behavior**
A character '6' printed to console was expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/70840444/141293580-5da84961-4ef4-499d-bb4a-3bd513b6bba4.png)

**Desktop (please complete the following information):**
 - OS: Windows NT 10 Home
 - Browser: I dont think this is needed.
 - Version: current sources (trunk)

**Smartphone (please complete the following information):**
 I don't think this is neded.

**Additional context**
I think that that the `1` should be replaced with `-1` in this snippet:
```python
        while self.token_stack and self.token_stack[1].satisfied:
            yield self.token_stack.pop()
```
(lines 39-40 in `parse()` in interpreter\parsing.py), because it works then and the rest of scripts that had worked before work too.

**Comment by rbaltrusch** [comment] 2021-11-11 22:07
Hello @ankiedos , thanks for raising the issue.

I have looked into it and you are right, the index should have been -1 and that would fix the error.

I have simplified the logic in in the Parser class a little bit today, as it was getting a bit out of hand, and ended up noticing that the final token.satisfied check is more or less redundant, so I removed it in commit 7510f9d3fcb3be8890b876cd603adba69f8ef3de (this fixes the bug you describe).

With the changed functionality, Parser.parse now returns any remaining tokens on the token stack, whether they are satisfied or not. This is desireable when parsing source code files, as you will get a SyntaxError describing the unsatisfied tokens. This is not desireable for an interactive console environment, such as the Python console, but this is currently out of scope for Natscript.

There is still some strange behaviour left to be fixed, which is caused by optional tokens (such as the optional else clause for if-statements) confusing the parser.

**Closed by rbaltrusch** 2021-11-11 22:07 UTC
Labels: bug, good first issue
